### ISSUE TITLE
What is musabgultekin/functionary-7b-v1

### ISSUE THREAD

**Issue by StudyingLover** [musabgultekin/functionary#17]
Hey,I think your repo is interesting, but I have some questions.
In your README.md, run `python3 server.py --model "musabgultekin/functionary-7b-v1"` to start server ,but what is musabgultekin/functionary-7b-v1 an how can I get it.

**Comment by StudyingLover** [comment]
Oooooo,I have a another question, is it same to Code Interpreter ? Or what's difference about them?

**Comment by musabgultekin** [comment]
> Hey,I think your repo is interesting, but I have some questions. In your README.md, run `python3 server.py --model "musabgultekin/functionary-7b-v1"` to start server ,but what is musabgultekin/functionary-7b-v1 an how can I get it.

Its the model's name on huggingface.


> Oooooo,I have a another question, is it same to Code Interpreter ? Or what's difference about them?

No its not, this allows calling arbitrary functions in any language. Not python code.
