### ISSUE TITLE
openai.api_key required?

### ISSUE THREAD

**Issue by willswordh** [musabgultekin/functionary#5]
Hi, great work! I am a bit confused from the readme that openai.api_key is needed to run your model? Thanks!

**Comment by musabgultekin** [comment]
Its not required but its just how we make it work for openai package . Setting it empty string is enough.

**Comment by musabgultekin** [comment]
added clarification: https://github.com/musabgultekin/functionary/commit/77bb0855ccfe7461632fd5f40164439926af029d

Thanks for the question!
