### ISSUE TITLE
hello,  i had some questions if youve got a sec

### ISSUE THREAD

**Issue by Alignment-Lab-AI** [musabgultekin/functionary#6]
im with Alignment Lab AI, were currently operating a pile of open sourced projects and i was reaching out because training a model to do this has been one of my personal goals for a while now, you mentioned you wanted to train a 13b variant, and i believe i have the tools on hand to generate a dataset of arbitrary size to your needs, would you have some spare time to discuss some of this with me in the next few days?

**Comment by musabgultekin** [comment]
Hi, 
Yeah, sure definitely! You can message me from linkedin and we can chat
